const DEFAULT_LANGUAGE='en';
let translations={};
async function loadTranslations(){const response=await fetch('translations.json',{cache:'no-store'});if(!response.ok){throw new Error('Unable to load translations.json');}translations=await response.json();window.translations=translations;return translations;}
function getNestedValue(object,path){return path.split('.').reduce(function(accumulator,key){return accumulator&&Object.prototype.hasOwnProperty.call(accumulator,key)?accumulator[key]:undefined;},object);}
function getAvailableLanguages(){if(!translations||typeof translations!=='object'){return [];}return Object.keys(translations).filter(function(key){return translations[key]&&typeof translations[key]==='object'&&!Array.isArray(translations[key]);});}
function getSavedLanguage(){const saved=localStorage.getItem('siteLanguage');return saved||'';}
function saveLanguage(language){localStorage.setItem('siteLanguage',language);}
function getInitialLanguage(){const languages=getAvailableLanguages();const saved=getSavedLanguage();const browser=(navigator.language||navigator.userLanguage||DEFAULT_LANGUAGE).slice(0,2).toLowerCase();if(saved&&languages.includes(saved)){return saved;}if(languages.includes(browser)){return browser;}if(languages.includes(DEFAULT_LANGUAGE)){return DEFAULT_LANGUAGE;}return languages[0]||DEFAULT_LANGUAGE;}
function updateTextNodes(language){document.querySelectorAll('[data-i18n]').forEach(function(element){const key=element.getAttribute('data-i18n');const value=getNestedValue(translations[language],key);if(typeof value!=='string'){return;}if(element.hasAttribute('data-i18n-html')){element.innerHTML=value;return;}if(/<[^>]+>/.test(value)){element.innerHTML=value;return;}element.textContent=value;});}
function updateAttributeNodes(language){document.querySelectorAll('[data-i18n-attr]').forEach(function(element){const attributeMap=element.getAttribute('data-i18n-attr');if(!attributeMap){return;}attributeMap.split(',').forEach(function(pair){const parts=pair.split(':');const attributeName=parts[0]?parts[0].trim():'';const key=parts[1]?parts[1].trim():'';const value=getNestedValue(translations[language],key);if(attributeName&&typeof value==='string'){element.setAttribute(attributeName,value);}});});}
function updateDocumentLanguage(language){document.documentElement.setAttribute('lang',language);}
function populateLanguageSwitcher(language){const switcher=document.getElementById('languageSwitcher');const wrap=document.getElementById('langWrap');const languages=getAvailableLanguages();if(!switcher||!wrap){return;}switcher.innerHTML='';if(languages.length<=1){wrap.classList.remove('is-visible');return;}languages.forEach(function(code){const option=document.createElement('option');option.value=code;option.textContent=code.toUpperCase();switcher.appendChild(option);});switcher.value=language;wrap.classList.add('is-visible');}
function setLanguage(language){const languages=getAvailableLanguages();const resolved=languages.includes(language)?language:(languages.includes(DEFAULT_LANGUAGE)?DEFAULT_LANGUAGE:languages[0]||DEFAULT_LANGUAGE);updateDocumentLanguage(resolved);updateTextNodes(resolved);updateAttributeNodes(resolved);populateLanguageSwitcher(resolved);saveLanguage(resolved);window.currentLanguage=resolved;}
function bindLanguageSwitcher(){const switcher=document.getElementById('languageSwitcher');if(!switcher){return;}switcher.addEventListener('change',function(event){setLanguage(event.target.value);});}
async function initI18n(){try{await loadTranslations();bindLanguageSwitcher();setLanguage(getInitialLanguage());}catch(error){console.error('i18n initialization failed:',error);}}
window.setLanguage=setLanguage;
window.addEventListener('DOMContentLoaded',initI18n);